### ISSUE TITLE
Default animation isn't displayed

### ISSUE THREAD

**Issue by sh-dave** [wighawag/spriter#2]
Hi wighawag,

trying out your spriter+spriterkha library here and i noticed that the default animation somehow isn't displayed. In the EntityInstance ctor you start it with _play(entity.animations[0]), but nothing is ever visible. I have to manually call EntityInstance.play('idle') again to actually see something rendered.

Should this work or am i supposed to call EntityInstance.play() again?

**Comment by wighawag** [comment]
it should have work without calling play() again.
Are you using the demo provided or are you using your own spriter file ?
if so could you send it to me so I can check. Anyway I ll have a look
not right now thought, maybe tonight

**Comment by wighawag** [comment]
I just had a quick look and the only thing I can think of right now is that there is other animation apart from "idle" and the first one (picked up by the cstor) is the one not visible. Of course, it could still mean there is some issue with the library if that animation should be visible.

**Comment by sh-dave** [comment]
i just tried your spriter_test and it's happening there as well. i have to press space, only then it's displayed

**Comment by sh-dave** [comment]
hm, it seems it's only happening on the flash target, html5 shows the animation

**Comment by wighawag** [comment]
Ok, found the problem, an uninitialised variable (Flash do not initialise to zero, js do) : https://github.com/wighawag/spriter/commit/251111d2f56cedbe98b9488ee43dbae935a5e0b7
